# Generated by Django 6.0.5 on 2026-07-04 19:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('ingestion', '0002_add_failed_status_and_scope_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GwpSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('gwp_co2', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('gwp_ch4', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gwp_n2o', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('source', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='e.g. DIESEL_STATIONARY', max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('default_scope', models.CharField(choices=[('SCOPE_1', 'Scope 1 (Direct)'), ('SCOPE_2', 'Scope 2 (Indirect Electricity)'), ('SCOPE_3', 'Scope 3 (Other Indirect)')], max_length=20)),
                ('base_unit', models.CharField(help_text='Canonical activity unit (L, kWh, km)', max_length=32)),
                ('gas_basis', models.CharField(default='CO2E', max_length=16)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['code'],
                'indexes': [models.Index(fields=['default_scope'], name='ix_acttype_scope')],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='ISO-3166 / GLOBAL / EU', max_length=16, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='carbon.region')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='OrgFactorPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferred_publisher', models.CharField(blank=True, choices=[('DEFRA', 'DEFRA / UK Gov GHG Conversion Factors'), ('EPA', 'US EPA'), ('IPCC', 'IPCC'), ('COUNTRY', 'Country-specific'), ('CUSTOM', 'Custom / Organization-provided')], max_length=16)),
                ('strict_mode', models.BooleanField(default=False, help_text='If true, do not fall back to GLOBAL factors.')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factor_policy', to='core.organization')),
                ('default_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carbon.region')),
            ],
        ),
        migrations.CreateModel(
            name='EmissionFactorDataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('publisher', models.CharField(choices=[('DEFRA', 'DEFRA / UK Gov GHG Conversion Factors'), ('EPA', 'US EPA'), ('IPCC', 'IPCC'), ('COUNTRY', 'Country-specific'), ('CUSTOM', 'Custom / Organization-provided')], max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(help_text='Publisher version, e.g. 2024.1', max_length=64)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('SUPERSEDED', 'Superseded')], default='DRAFT', max_length=16)),
                ('valid_from', models.DateField(help_text="Start of the effective window for this dataset's factors")),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('priority', models.IntegerField(default=100, help_text='Resolution tie-breaker (higher wins)')),
                ('publication_date', models.DateField(blank=True, help_text='When the publisher released it', null=True)),
                ('import_timestamp', models.DateTimeField(auto_now_add=True, help_text='When ScopeTrace imported it')),
                ('checksum', models.CharField(blank=True, help_text='sha256 of the imported source', max_length=64)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True)),
                ('import_notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_datasets', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='datasets', to='carbon.region')),
            ],
            options={
                'verbose_name': 'Emission Factor Dataset',
                'ordering': ['-import_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit', models.CharField(help_text="The 'per' unit the factor is expressed in", max_length=32)),
                ('co2e_per_unit', models.DecimalField(decimal_places=12, max_digits=30)),
                ('co2_per_unit', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('ch4_per_unit', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('n2o_per_unit', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('valid_from', models.DateField(blank=True, help_text='Overrides dataset window if set', null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('methodology', models.TextField(blank=True)),
                ('uncertainty_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('source_ref', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factors', to='carbon.activitytype')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='carbon.emissionfactordataset')),
                ('gwp_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factors', to='carbon.gwpset')),
                ('region', models.ForeignKey(blank=True, help_text='Region override; null inherits the dataset/global scope', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factors', to='carbon.region')),
            ],
            options={
                'verbose_name': 'Emission Factor',
            },
        ),
        migrations.CreateModel(
            name='ActivityMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_source_type', models.CharField(choices=[('SAP_FUEL', 'SAP Fuel & Procurement CSV'), ('UTILITY_ELECTRICITY', 'Utility Electricity Portal CSV'), ('CORP_TRAVEL', 'Corporate Travel JSON')], max_length=50)),
                ('match_key', models.CharField(blank=True, help_text='Optional attribute value; blank = default for the source type', max_length=64)),
                ('priority', models.IntegerField(default=100)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mappings', to='carbon.activitytype')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carbon.region')),
            ],
            options={
                'verbose_name': 'Activity Mapping',
            },
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_unit', models.CharField(max_length=32)),
                ('to_unit', models.CharField(max_length=32)),
                ('dimension', models.CharField(choices=[('VOLUME', 'Volume'), ('ENERGY', 'Energy'), ('DISTANCE', 'Distance'), ('MASS', 'Mass')], max_length=16)),
                ('factor', models.DecimalField(decimal_places=12, help_text='1 from_unit = factor to_unit', max_digits=30)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('from_unit', 'to_unit'), name='unique_unit_conversion')],
            },
        ),
        migrations.CreateModel(
            name='EmissionCalculation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_current', models.BooleanField(default=True)),
                ('factor_publisher', models.CharField(blank=True, max_length=16)),
                ('factor_version', models.CharField(blank=True, max_length=64)),
                ('factor_value', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('factor_unit', models.CharField(blank=True, max_length=32)),
                ('activity_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('activity_unit', models.CharField(blank=True, max_length=32)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('co2e_tonnes', models.DecimalField(blank=True, decimal_places=9, max_digits=20, null=True)),
                ('gas_breakdown', models.JSONField(blank=True, default=dict)),
                ('calculation_trace', models.JSONField(blank=True, default=dict)),
                ('resolution_status', models.CharField(choices=[('CALCULATED', 'Calculated'), ('UNRESOLVED_NO_FACTOR', 'No matching factor'), ('UNRESOLVED_NO_ACTIVITY_TYPE', 'No activity-type mapping'), ('EXCLUDED_FAILED', 'Excluded (failed validation)')], default='CALCULATED', max_length=32)),
                ('engine_version', models.CharField(default='1.0', max_length=16)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('activity_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calculations', to='carbon.activitytype')),
                ('emission_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='ingestion.emissionrecord')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_calculations', to='core.organization')),
                ('emission_factor', models.ForeignKey(blank=True, help_text='PROTECTed: a factor used by a calculation cannot be deleted', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calculations', to='carbon.emissionfactor')),
            ],
            options={
                'verbose_name': 'Emission Calculation',
                'ordering': ['-calculated_at'],
                'indexes': [models.Index(fields=['organization', 'is_current'], name='ix_calc_org_current'), models.Index(fields=['emission_record', 'is_current'], name='ix_calc_record_current'), models.Index(fields=['organization', 'resolution_status'], name='ix_calc_org_status'), models.Index(fields=['organization', 'activity_type'], name='ix_calc_org_acttype')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('emission_record',), name='unique_current_calc_per_record')],
            },
        ),
        migrations.AddIndex(
            model_name='emissionfactordataset',
            index=models.Index(fields=['publisher', 'status'], name='ix_dataset_pub_status'),
        ),
        migrations.AddIndex(
            model_name='emissionfactordataset',
            index=models.Index(fields=['status', 'valid_from'], name='ix_dataset_status_from'),
        ),
        migrations.AddConstraint(
            model_name='emissionfactordataset',
            constraint=models.UniqueConstraint(fields=('publisher', 'version', 'region'), name='unique_dataset_publisher_version_region'),
        ),
        migrations.AddIndex(
            model_name='emissionfactor',
            index=models.Index(fields=['activity_type', 'region'], name='ix_factor_type_region'),
        ),
        migrations.AddIndex(
            model_name='emissionfactor',
            index=models.Index(fields=['dataset'], name='ix_factor_dataset'),
        ),
        migrations.AddIndex(
            model_name='emissionfactor',
            index=models.Index(fields=['activity_type', 'valid_from', 'valid_to'], name='ix_factor_effective'),
        ),
        migrations.AddConstraint(
            model_name='emissionfactor',
            constraint=models.UniqueConstraint(fields=('dataset', 'activity_type', 'unit', 'region', 'valid_from'), name='unique_factor_scope'),
        ),
        migrations.AddIndex(
            model_name='activitymapping',
            index=models.Index(fields=['data_source_type', 'match_key'], name='ix_mapping_lookup'),
        ),
        migrations.AddConstraint(
            model_name='activitymapping',
            constraint=models.UniqueConstraint(fields=('data_source_type', 'match_key'), name='unique_activity_mapping'),
        ),
    ]
