# Generated by Django 6.0.5 on 2026-07-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon', '0001_initial'),
        ('core', '0001_initial'),
        ('ingestion', '0002_add_failed_status_and_scope_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissioncalculation',
            name='reporting_date',
            field=models.DateField(blank=True, help_text='Activity/emission date (drives time-series)', null=True),
        ),
        migrations.AddField(
            model_name='emissioncalculation',
            name='reporting_month',
            field=models.DateField(blank=True, help_text="First day of reporting_date's month (bucketing)", null=True),
        ),
        migrations.AddField(
            model_name='emissioncalculation',
            name='scope',
            field=models.CharField(blank=True, choices=[('SCOPE_1', 'Scope 1 (Direct)'), ('SCOPE_2', 'Scope 2 (Indirect Electricity)'), ('SCOPE_3', 'Scope 3 (Other Indirect)')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='emissioncalculation',
            index=models.Index(fields=['organization', 'is_current', 'scope'], name='ix_calc_org_scope'),
        ),
        migrations.AddIndex(
            model_name='emissioncalculation',
            index=models.Index(fields=['organization', 'is_current', 'reporting_date'], name='ix_calc_org_rdate'),
        ),
        migrations.AddIndex(
            model_name='emissioncalculation',
            index=models.Index(fields=['organization', 'is_current', 'reporting_month'], name='ix_calc_org_rmonth'),
        ),
    ]
