# Generated by Django 6.0.5 on 2026-07-07 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon', '0003_backfill_reporting_dimensions'),
        ('ingestion', '0008_workflow_status_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissioncalculation',
            name='emission_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculations', to='ingestion.emissionrecord'),
        ),
    ]
