"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
from decouple import config, Csv
from django.core.exceptions import ImproperlyConfigured
import dj_database_url
import os
import sys

# True while running the test suite — used to disable rate limiting so tests
# don't hit throttle ceilings.
_TESTING = 'test' in sys.argv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ---------------------------------------------------------------------------
# Core security configuration — FAILS CLOSED.
#
# Every default here is the safe production choice (DEBUG off, no wildcard
# hosts, CORS locked, no fallback secret). A missing or unsafe environment
# variable raises ImproperlyConfigured at boot instead of silently exposing
# the service. Convenience fallbacks are permitted ONLY when DEBUG is True.
# ---------------------------------------------------------------------------

# DEBUG defaults to False so an unset env var can never enable debug in prod.
DEBUG = config('DEBUG', default=False, cast=bool)

# SECRET_KEY: a throwaway key is allowed only in local debug. In production the
# variable is mandatory — booting without it is a hard error, not a weak default.
SECRET_KEY = config('SECRET_KEY', default='')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-local-development-only-do-not-use-in-production'
    else:
        raise ImproperlyConfigured(
            "SECRET_KEY environment variable is required when DEBUG=False."
        )

# ALLOWED_HOSTS defaults to localhost only — never '*'.
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())

# Render injects the external hostname at runtime — trust it automatically.
render_host = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if render_host and render_host not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(render_host)

# Reject wildcard hosts in production — it defeats Host-header validation.
if not DEBUG and '*' in ALLOWED_HOSTS:
    raise ImproperlyConfigured(
        "ALLOWED_HOSTS must not contain '*' when DEBUG=False. "
        "List the exact public hostname(s)."
    )


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party packages
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    'corsheaders',

    # Local apps
    'apps.core',
    'apps.accounts',
    'apps.ingestion',
    'apps.audit',
    'apps.carbon',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise serves static files efficiently in production (must be 2nd after SecurityMiddleware)
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# SQLite is permitted ONLY for local development (DEBUG=True). In production a
# DATABASE_URL pointing at managed PostgreSQL is mandatory. This prevents the
# app from silently falling back to an ephemeral SQLite file on a container's
# disk — which is wiped on every deploy/restart and was the root cause of the
# prior "DataSource disappears" / "ledger empty after deploy" data loss.

DATABASE_URL = config('DATABASE_URL', default='')
if not DATABASE_URL:
    if DEBUG:
        DATABASE_URL = f'sqlite:///{BASE_DIR / "db.sqlite3"}'
    else:
        raise ImproperlyConfigured(
            "DATABASE_URL environment variable is required when DEBUG=False. "
            "Point it at your managed PostgreSQL instance."
        )

DATABASES = {
    # conn_max_age keeps connections warm (persistent connections) in production.
    'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600),
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# WhiteNoise compressed manifest storage for production
STATICFILES_STORAGE = (
    'django.contrib.staticfiles.storage.StaticFilesStorage'
    if DEBUG
    else 'whitenoise.storage.CompressedManifestStaticFilesStorage'
)

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS Settings — locked down by default; allow-all must be opted into explicitly.
CORS_ALLOW_ALL_ORIGINS = config('CORS_ALLOW_ALL_ORIGINS', default=False, cast=bool)
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:5173,http://localhost:3000',
    cast=Csv(),
)

# CSRF trusted origins (needed for the admin/browsable API over HTTPS).
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=Csv())
if render_host:
    CSRF_TRUSTED_ORIGINS.append(f'https://{render_host}')

# Production security hardening (active when DEBUG=False).
# The TLS-terminating toggles are env-overridable so the stack can also run
# behind plain HTTP locally (e.g. Docker Compose) without redirect loops,
# while defaulting to fully hardened in real deployments.
if not DEBUG:
    # Trust the proxy's X-Forwarded-Proto so SSL redirect + secure cookies work
    # behind Render's (and most PaaS) TLS-terminating load balancer.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=True, cast=bool)
    SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=True, cast=bool)
    CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=True, cast=bool)
    SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=31536000, cast=int)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True


# ---------------------------------------------------------------------------
# Django REST Framework — centralized configuration.
#
# These are the framework's CURRENT effective defaults, made explicit so future
# phases change auth/permissions/pagination in ONE place instead of touching
# every view. Nothing here changes today's behavior.
#
# See docs/ARCHITECTURE_INTEGRATION.md for the full integration map.
# ---------------------------------------------------------------------------
REST_FRAMEWORK = {
    # JWT is the primary API authentication. SessionAuthentication is kept so the
    # DRF browsable API and Django admin remain usable during development.
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    # Secure default: every endpoint requires authentication unless it explicitly
    # opts out (the auth/login and health endpoints do).
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # Pagination (Phase 4): unbounded transactional lists return a
    # {count, next, previous, results} envelope. Bounded selector endpoints
    # (organizations/datasources/activity-types) opt out via pagination_class=None.
    'DEFAULT_PAGINATION_CLASS': 'apps.core.pagination.StandardResultsPagination',
    'PAGE_SIZE': 50,
    # Standardized filtering.
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    # Rate limiting. Rates are None under test (no throttling); the 'login' scope
    # is applied to the token endpoint to blunt credential-stuffing.
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': None if _TESTING else config('THROTTLE_ANON', default='100/hour'),
        'user': None if _TESTING else config('THROTTLE_USER', default='2000/hour'),
        'login': None if _TESTING else config('THROTTLE_LOGIN', default='10/min'),
    },
}

# ---------------------------------------------------------------------------
# SimpleJWT — access/refresh tokens with rotation + blacklist on logout.
# ---------------------------------------------------------------------------
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=config('JWT_ACCESS_MINUTES', default=15, cast=int)),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=config('JWT_REFRESH_DAYS', default=7, cast=int)),
    # Rotation: each refresh issues a new refresh token and blacklists the old one.
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}


# ---------------------------------------------------------------------------
# Future-integration seams (INERT — declared here, consumed in later phases).
#
# Declaring these now means later phases add only the consuming code, not new
# configuration plumbing. Everything defaults to "off" and changes no behavior.
# ---------------------------------------------------------------------------

# Redis — Phase 4 caching (Metrics API) and Phase 5 Celery broker/result backend.
REDIS_URL = config('REDIS_URL', default='')

# Celery — Phase 5 async ingestion + scheduled emission-factor refresh.
# Broker/backend fall back to REDIS_URL when not set explicitly. EAGER mode runs
# tasks synchronously inline (no broker needed) — used in local DEBUG dev and
# ALWAYS under the test runner, so CI never needs a live Redis to run the suite.
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default=REDIS_URL)
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default=REDIS_URL)
CELERY_TASK_ALWAYS_EAGER = config(
    'CELERY_TASK_ALWAYS_EAGER', default=(DEBUG or _TESTING), cast=bool
)
# Eager mode re-raises task exceptions synchronously instead of swallowing them
# into the (unused, in eager mode) result backend — failures surface immediately
# in local dev and in tests.
CELERY_TASK_EAGER_PROPAGATES = True

CELERY_TIMEZONE = TIME_ZONE
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
# Explicit opt-in ahead of the Celery 6.0 default flip, so a worker starting
# before Redis is ready retries the connection instead of crashing on boot.
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# Default queue name, explicit now so Phase 5e can introduce a dedicated
# dead-letter queue alongside it without renaming this one.
CELERY_TASK_DEFAULT_QUEUE = config('CELERY_TASK_DEFAULT_QUEUE', default='celery')

# acks_late + prefetch=1: a task is acknowledged only after it finishes, so a
# crashed worker's in-flight task is redelivered rather than lost, and adding
# worker replicas distributes load evenly instead of one worker prefetching a
# queue's worth of work. Requires tasks to be safe to re-run if redelivered
# (the idempotency guard Phase 5b's async ingestion is designed around).
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

# Task/worker events — no consumer yet, but zero-cost to enable now so Flower /
# `celery events` work without a config change when Phase 5h adds them.
CELERY_WORKER_SEND_TASK_EVENTS = True
CELERY_TASK_SEND_SENT_EVENT = True

# Cache — use Redis when configured, otherwise Django's default local-memory
# cache. No behavior change today (nothing reads the cache yet); the Phase 4
# Metrics API will use the 'default' alias.
if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
        }
    }

# ---------------------------------------------------------------------------
# Durable file storage (Phase 5b) — StorageService abstraction.
#
# STORAGE_BACKEND selects the concrete provider. Application code (ingestion,
# future features) must depend only on apps.core.storage.get_storage_service()
# and the StorageService interface — never import a concrete provider or SDK
# directly. See apps/core/storage/ for the interface + providers.
#
# Fails closed exactly like DATABASE_URL: local filesystem storage is a
# development-only convenience; production must explicitly select 's3'.
# Docker Compose runs a MinIO container (S3-compatible) and sets
# STORAGE_BACKEND=s3 with AWS_S3_ENDPOINT_URL pointing at it, so the
# production code path is exercised in local dev too — local filesystem
# storage is reserved for `manage.py runserver` / the test runner only.
# ---------------------------------------------------------------------------
STORAGE_BACKEND = config('STORAGE_BACKEND', default='local' if DEBUG else '')
if not DEBUG and STORAGE_BACKEND != 's3':
    raise ImproperlyConfigured(
        "STORAGE_BACKEND must be 's3' when DEBUG=False. "
        "Local filesystem storage is a development-only convenience."
    )

# Local filesystem backend (LocalFileSystemStorageService).
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
# Base origin used to build fully-qualified download URLs locally, so
# generate_download_url() returns an absolute URL exactly like the S3
# provider's presigned URL — callers never special-case the backend.
MEDIA_BASE_URL = config('MEDIA_BASE_URL', default='http://localhost:8000')

# S3-compatible backend (S3StorageService) — also serves Cloudflare R2 /
# Backblaze B2 / MinIO, since they all speak the S3 API; only the endpoint
# URL and addressing style change.
AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID', default='')
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY', default='')
AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME', default='')
AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME', default='auto')
# Blank = real AWS S3. Set for R2 / B2 / MinIO (e.g. http://minio:9000 in Compose).
AWS_S3_ENDPOINT_URL = config('AWS_S3_ENDPOINT_URL', default='')
# MinIO requires 'path' addressing (bucket.in.path, not bucket.as.subdomain);
# real AWS S3 / R2 / B2 use 'virtual'.
AWS_S3_ADDRESSING_STYLE = config('AWS_S3_ADDRESSING_STYLE', default='virtual')
AWS_QUERYSTRING_EXPIRE = config('AWS_S3_URL_EXPIRE_SECONDS', default=3600, cast=int)

if STORAGE_BACKEND == 's3' and not DEBUG:
    _required_s3_vars = {
        'AWS_ACCESS_KEY_ID': AWS_ACCESS_KEY_ID,
        'AWS_SECRET_ACCESS_KEY': AWS_SECRET_ACCESS_KEY,
        'AWS_STORAGE_BUCKET_NAME': AWS_STORAGE_BUCKET_NAME,
    }
    _missing_s3_vars = [name for name, value in _required_s3_vars.items() if not value]
    if _missing_s3_vars:
        raise ImproperlyConfigured(
            f"STORAGE_BACKEND=s3 requires {', '.join(_missing_s3_vars)} to be set."
        )


# Phased-rollout feature flags (all default off). Future code gates on these so
# incomplete features can merge dark and be enabled per-environment.
FEATURE_JWT_AUTH = config('FEATURE_JWT_AUTH', default=False, cast=bool)
FEATURE_ENFORCE_TENANT_SCOPE = config('FEATURE_ENFORCE_TENANT_SCOPE', default=False, cast=bool)
FEATURE_EMISSION_FACTORS = config('FEATURE_EMISSION_FACTORS', default=False, cast=bool)


# ---------------------------------------------------------------------------
# Logging — structured console logging (captured by Render / Docker stdout).
# Application loggers (apps.*) emit INFO+; tune via LOG_LEVEL / DJANGO_LOG_LEVEL.
# ---------------------------------------------------------------------------
LOG_LEVEL = config('LOG_LEVEL', default='INFO')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': LOG_LEVEL,
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': config('DJANGO_LOG_LEVEL', default='INFO'),
            'propagate': False,
        },
        # First-party application code (apps.ingestion, apps.core, ...).
        'apps': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
    },
}
