"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv
from django.core.exceptions import ImproperlyConfigured
import dj_database_url
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ---------------------------------------------------------------------------
# Core security configuration — FAILS CLOSED.
#
# Every default here is the safe production choice (DEBUG off, no wildcard
# hosts, CORS locked, no fallback secret). A missing or unsafe environment
# variable raises ImproperlyConfigured at boot instead of silently exposing
# the service. Convenience fallbacks are permitted ONLY when DEBUG is True.
# ---------------------------------------------------------------------------

# DEBUG defaults to False so an unset env var can never enable debug in prod.
DEBUG = config('DEBUG', default=False, cast=bool)

# SECRET_KEY: a throwaway key is allowed only in local debug. In production the
# variable is mandatory — booting without it is a hard error, not a weak default.
SECRET_KEY = config('SECRET_KEY', default='')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-local-development-only-do-not-use-in-production'
    else:
        raise ImproperlyConfigured(
            "SECRET_KEY environment variable is required when DEBUG=False."
        )

# ALLOWED_HOSTS defaults to localhost only — never '*'.
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())

# Render injects the external hostname at runtime — trust it automatically.
render_host = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if render_host and render_host not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(render_host)

# Reject wildcard hosts in production — it defeats Host-header validation.
if not DEBUG and '*' in ALLOWED_HOSTS:
    raise ImproperlyConfigured(
        "ALLOWED_HOSTS must not contain '*' when DEBUG=False. "
        "List the exact public hostname(s)."
    )


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party packages
    'rest_framework',
    'corsheaders',
    
    # Local apps
    'apps.core',
    'apps.ingestion',
    'apps.audit',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise serves static files efficiently in production (must be 2nd after SecurityMiddleware)
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# SQLite is permitted ONLY for local development (DEBUG=True). In production a
# DATABASE_URL pointing at managed PostgreSQL is mandatory. This prevents the
# app from silently falling back to an ephemeral SQLite file on a container's
# disk — which is wiped on every deploy/restart and was the root cause of the
# prior "DataSource disappears" / "ledger empty after deploy" data loss.

DATABASE_URL = config('DATABASE_URL', default='')
if not DATABASE_URL:
    if DEBUG:
        DATABASE_URL = f'sqlite:///{BASE_DIR / "db.sqlite3"}'
    else:
        raise ImproperlyConfigured(
            "DATABASE_URL environment variable is required when DEBUG=False. "
            "Point it at your managed PostgreSQL instance."
        )

DATABASES = {
    # conn_max_age keeps connections warm (persistent connections) in production.
    'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600),
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# WhiteNoise compressed manifest storage for production
STATICFILES_STORAGE = (
    'django.contrib.staticfiles.storage.StaticFilesStorage'
    if DEBUG
    else 'whitenoise.storage.CompressedManifestStaticFilesStorage'
)

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS Settings — locked down by default; allow-all must be opted into explicitly.
CORS_ALLOW_ALL_ORIGINS = config('CORS_ALLOW_ALL_ORIGINS', default=False, cast=bool)
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:5173,http://localhost:3000',
    cast=Csv(),
)

# CSRF trusted origins (needed for the admin/browsable API over HTTPS).
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=Csv())
if render_host:
    CSRF_TRUSTED_ORIGINS.append(f'https://{render_host}')

# Production security hardening (active when DEBUG=False).
# The TLS-terminating toggles are env-overridable so the stack can also run
# behind plain HTTP locally (e.g. Docker Compose) without redirect loops,
# while defaulting to fully hardened in real deployments.
if not DEBUG:
    # Trust the proxy's X-Forwarded-Proto so SSL redirect + secure cookies work
    # behind Render's (and most PaaS) TLS-terminating load balancer.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=True, cast=bool)
    SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=True, cast=bool)
    CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=True, cast=bool)
    SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=31536000, cast=int)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
