"""
Phase 6e — compliance report endpoints. See
docs/adr/0002-compliance-reports-on-demand-not-persisted.md for why these
are on-demand (no persisted report model) and apps/carbon/services/
reports.py for the underlying query/aggregation logic.
"""
import csv
import logging
from datetime import date, datetime
from decimal import Decimal

from django.http import StreamingHttpResponse
from django.utils import timezone
from rest_framework import serializers
from rest_framework.exceptions import PermissionDenied
from rest_framework.response import Response
from rest_framework.views import APIView

from apps.accounts.permissions import CanViewActivity
from apps.accounts.tenancy import resolve_tenant_context
from apps.carbon.models import Scope
from apps.carbon.services.reports import (
    CSV_HEADER,
    JSON_LINE_ITEM_CAP,
    audit_chain_snapshot,
    build_line_items_queryset,
    compliance_summary,
    csv_row,
    serialize_line_item,
)

logger = logging.getLogger(__name__)


def _jsonify(value):
    """Decimal -> str, date/datetime -> ISO -- same normalization
    apps.carbon.metrics_views._jsonify performs, duplicated locally (an
    8-line pure function) rather than importing a private helper across
    modules for a report payload with a different shape."""
    if isinstance(value, Decimal):
        return str(value)
    if isinstance(value, (date, datetime)):
        return value.isoformat()
    if isinstance(value, dict):
        return {k: _jsonify(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [_jsonify(v) for v in value]
    return value


class ComplianceReportFilterSerializer(serializers.Serializer):
    """Unlike MetricsFilterSerializer's optional date range, a compliance
    report always covers a defined reporting period -- GHG Protocol /
    CSRD reports are never open-ended."""
    date_from = serializers.DateField(required=True)
    date_to = serializers.DateField(required=True)
    scope = serializers.ChoiceField(choices=Scope.choices, required=False)

    def validate(self, data):
        if data["date_from"] > data["date_to"]:
            raise serializers.ValidationError("date_from must not be after date_to.")
        return data


class _BaseComplianceReportView(APIView):
    """Org Admin / Auditor only -- a compliance report is an audit
    artifact, matching the RBAC already used for /api/audit/verify/ and
    /api/metrics/activity/, not the broader IsOrgMember dashboards use."""
    permission_classes = [CanViewActivity]

    def _resolve(self, request):
        ctx = resolve_tenant_context(request)
        if ctx.organization is None:
            raise PermissionDenied(
                "Select an organization (X-Organization-ID) to generate a compliance report."
            )
        fs = ComplianceReportFilterSerializer(data=request.query_params)
        fs.is_valid(raise_exception=True)
        d = fs.validated_data
        return ctx.organization, d["date_from"], d["date_to"], d.get("scope")

    def _log_generation(self, request, organization, date_from, date_to, scope, fmt):
        # Phase 6f: INFO, not an AuditTrail entry (see the ADR's "considered
        # and rejected" section -- report generation stays a pure read).
        # Purely for operational visibility: who pulled which compliance
        # report, for which org/period, in what format.
        logger.info(
            "Compliance report (%s) generated by %s for org=%s period=%s..%s scope=%s",
            fmt, request.user.username if request.user.is_authenticated else None,
            organization.id, date_from, date_to, scope or "all",
        )


class ComplianceReportView(_BaseComplianceReportView):
    """GET /api/reports/compliance/ -- JSON compliance report: metadata,
    audit-chain status, aggregate summary, and up to JSON_LINE_ITEM_CAP
    line items. Use .../compliance/csv/ for a larger, streamed export."""

    def get(self, request):
        organization, date_from, date_to, scope = self._resolve(request)
        self._log_generation(request, organization, date_from, date_to, scope, "json")

        qs = build_line_items_queryset(organization, date_from, date_to, scope)
        total_count = qs.count()
        line_items = [serialize_line_item(calc) for calc in qs[:JSON_LINE_ITEM_CAP]]

        payload = {
            "organization": {"id": str(organization.id), "name": organization.name},
            "period": {"date_from": date_from, "date_to": date_to},
            "scope": scope,
            "generated_at": timezone.now(),
            "generated_by": request.user.username if request.user.is_authenticated else None,
            "audit_chain": audit_chain_snapshot(organization),
            "summary": compliance_summary(organization, date_from, date_to, scope),
            "line_items": line_items,
            "line_item_count": total_count,
            "truncated": total_count > JSON_LINE_ITEM_CAP,
        }
        return Response(_jsonify(payload))


class _Echo:
    """A file-like object that returns each written row (for csv.writer) --
    same pattern as apps.ingestion.export_views._Echo."""
    def write(self, value):
        return value


class ComplianceReportCSVView(_BaseComplianceReportView):
    """GET /api/reports/compliance/csv/ -- streaming CSV of compliance
    report line items (uncapped, unlike the JSON endpoint). Summary/
    audit-chain metadata isn't representable in a flat CSV; use the JSON
    endpoint for that."""

    def get(self, request):
        organization, date_from, date_to, scope = self._resolve(request)
        self._log_generation(request, organization, date_from, date_to, scope, "csv")
        qs = build_line_items_queryset(organization, date_from, date_to, scope)

        writer = csv.writer(_Echo())

        def stream():
            yield writer.writerow(CSV_HEADER)
            for calc in qs.iterator(chunk_size=2000):
                yield writer.writerow(csv_row(calc))

        response = StreamingHttpResponse(stream(), content_type="text/csv")
        filename = f"scopetrace_compliance_{date_from.isoformat()}_{date_to.isoformat()}.csv"
        response["Content-Disposition"] = f'attachment; filename="{filename}"'
        return response
