# Generated by Django 6.0.5 on 2026-07-07 23:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantAIPolicy',
            fields=[
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ai_policy', serialize=False, to='core.organization')),
                ('ai_enabled', models.BooleanField(default=False)),
                ('provider_override', models.CharField(blank=True, max_length=50)),
                ('model_override', models.CharField(blank=True, max_length=100)),
                ('monthly_budget_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Null = use the platform default budget (settings.AI_DEFAULT_MONTHLY_BUDGET_USD).', max_digits=10, null=True)),
                ('egress_tier', models.CharField(choices=[('REDACTED', 'Redacted (default -- PII/identifier scrubbing before any external call)'), ('RAW', 'Raw (explicit opt-in, no redaction)'), ('NO_EGRESS', 'No egress (only zero-egress providers, e.g. echo/self-hosted, permitted)')], default='REDACTED', max_length=20)),
                ('byo_api_key_ref', models.CharField(blank=True, help_text='Reference/secret-name for a tenant-supplied API key (e.g. an env var name or secrets-manager path) -- never the raw key value itself.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIPromptVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Prompt template name, e.g. 'foundation.selftest' (stable across versions).", max_length=100)),
                ('version', models.PositiveIntegerField(help_text='Monotonically increasing per `name`, assigned at first registration of a new template_hash.')),
                ('template_hash', models.CharField(help_text='SHA-256 hex digest of template_text -- what actually varies per version.', max_length=64)),
                ('template_text', models.TextField(help_text='The template itself, verbatim. Not tenant data -- this is our own prompt authoring, safe to store in full for audit/reproducibility.')),
                ('response_schema_id', models.CharField(help_text="Identifier of the JSON schema this prompt version's response must validate against.", max_length=100)),
                ('response_schema_version', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name', '-version'], name='ai_aiprompt_name_963a8d_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'version'), name='ai_promptversion_unique_name_version'), models.UniqueConstraint(fields=('name', 'template_hash'), name='ai_promptversion_unique_name_hash')],
            },
        ),
        migrations.CreateModel(
            name='AIInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capability', models.CharField(help_text="Short code for the calling feature, e.g. 'foundation.selftest'. Free text like AuditTrail.action -- new capabilities never require a migration.", max_length=100)),
                ('provider', models.CharField(help_text="Adapter name: 'anthropic' | 'openai' | 'echo'.", max_length=50)),
                ('model_id', models.CharField(max_length=100)),
                ('model_snapshot', models.CharField(blank=True, max_length=100)),
                ('provider_request_id', models.CharField(blank=True, max_length=200)),
                ('prompt_template_hash', models.CharField(blank=True, max_length=64)),
                ('rendered_input_hash', models.CharField(blank=True, max_length=64)),
                ('context_provenance', models.JSONField(blank=True, default=list, help_text="List of record/metric ids that formed the prompt's context -- the retrieval analog of a compliance report's line-item provenance.")),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='temperature/top_p/max_tokens/seed/stop/response_schema_id/response_schema_version.')),
                ('response_hash', models.CharField(blank=True, max_length=64)),
                ('schema_valid', models.BooleanField(help_text='Null = no schema was expected for this call.', null=True)),
                ('outcome', models.CharField(choices=[('OK', 'Ok'), ('DEGRADED', 'Degraded (succeeded, but with a caveat -- reserved for future use)'), ('AI_DISABLED', 'AI disabled (globally or for this tenant)'), ('BUDGET_EXCEEDED', 'Budget exceeded'), ('EGRESS_BLOCKED', 'Egress policy blocked this call'), ('SCHEMA_INVALID', 'Response failed schema validation'), ('ERROR', 'Provider or gateway error')], max_length=20)),
                ('error_detail', models.TextField(blank=True, help_text='Sanitized error/validation detail -- never raw tenant data.')),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('egress_tier_applied', models.CharField(choices=[('REDACTED', 'Redacted (default -- PII/identifier scrubbing before any external call)'), ('RAW', 'Raw (explicit opt-in, no redaction)'), ('NO_EGRESS', 'No egress (only zero-egress providers, e.g. echo/self-hosted, permitted)')], max_length=20)),
                ('redaction_applied', models.BooleanField(default=False)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=100)),
                ('gateway_version', models.CharField(default='1', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Null for system-initiated calls (e.g. a scheduled task), not just a deleted user.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_interactions', to='core.organization')),
                ('prompt_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='ai.aipromptversion')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', '-created_at'], name='ai_aiintera_organiz_286678_idx'), models.Index(fields=['organization', 'idempotency_key'], name='ai_aiintera_organiz_6e9384_idx')],
            },
        ),
    ]
