# Generated by Django 6.0.5 on 2026-07-08 11:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('core', '0001_initial'),
        ('ingestion', '0009_soft_delete_and_retention'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnnotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capability', models.CharField(choices=[('ANOMALY_DETECTION', 'Anomaly Detection')], max_length=50)),
                ('explanation', models.TextField(help_text='Why the record is unusual.')),
                ('contributing_factors', models.JSONField(blank=True, default=list, help_text='List of likely contributing factors.')),
                ('confidence', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('suggested_investigation', models.TextField(help_text='What an analyst should look into next.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('interaction', models.ForeignKey(help_text='The exact gateway call that produced this annotation -- full reproducibility metadata lives there.', on_delete=django.db.models.deletion.PROTECT, related_name='annotations', to='ai.aiinteraction')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_annotations', to='core.organization')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_annotations', to='ingestion.emissionrecord')),
            ],
            options={
                'indexes': [models.Index(fields=['record', 'capability', '-created_at'], name='ai_aiannota_record__a1e150_idx'), models.Index(fields=['organization', '-created_at'], name='ai_aiannota_organiz_1c417d_idx')],
            },
        ),
    ]
