# Generated by Django 6.0.5 on 2026-07-08 12:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_aiannotation'),
        ('carbon', '0004_soft_delete_and_retention'),
        ('core', '0001_initial'),
        ('ingestion', '0009_soft_delete_and_retention'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIFactorRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confidence', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('explanation', models.TextField(help_text='Why this candidate (or none) fits.')),
                ('reasoning', models.TextField(help_text='Deterministic factors the AI weighed (region, date, publisher, ...).')),
                ('alternative_candidates', models.JSONField(blank=True, default=list, help_text='Other candidate labels the AI considered but ranked lower.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('interaction', models.ForeignKey(help_text='The exact gateway call that produced this recommendation.', on_delete=django.db.models.deletion.PROTECT, related_name='factor_recommendations', to='ai.aiinteraction')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_factor_recommendations', to='core.organization')),
                ('recommended_factor', models.ForeignKey(blank=True, help_text='Null if the AI recommended none of the candidates it was shown.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ai_recommendations', to='carbon.emissionfactor')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_factor_recommendations', to='ingestion.emissionrecord')),
            ],
            options={
                'indexes': [models.Index(fields=['record', '-created_at'], name='ai_aifactor_record__051c1d_idx'), models.Index(fields=['organization', '-created_at'], name='ai_aifactor_organiz_e7bb0c_idx')],
            },
        ),
    ]
