# Generated by Django 6.0.5 on 2026-07-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_aifactorrecommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiannotation',
            name='capability',
            field=models.CharField(choices=[('ANOMALY_DETECTION', 'Anomaly Detection'), ('VALIDATION_ASSISTANCE', 'Validation Assistance')], max_length=50),
        ),
    ]
