# Generated by Django 6.0.5 on 2026-07-08 14:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_alter_aiannotation_capability'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_conversations', to='core.organization')),
                ('user', models.ForeignKey(blank=True, help_text='Who started this conversation. Null if that user account was later deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIConversationMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('USER', 'User'), ('ASSISTANT', 'Assistant')], max_length=10)),
                ('content', models.TextField(help_text='The question (USER) or answer (ASSISTANT).')),
                ('citations', models.JSONField(blank=True, default=list, help_text='References into the retrieved context supporting the answer.')),
                ('confidence', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('unsupported_claim', models.BooleanField(default=False, help_text='True if the AI flagged its own answer as not fully supported by the context.')),
                ('retrieved_context', models.TextField(blank=True, help_text='The context block retrieved and shown to the AI for this turn.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='ai.aiconversation')),
                ('interaction', models.ForeignKey(blank=True, help_text='The exact gateway call that produced this message. Null for USER-role messages.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversation_messages', to='ai.aiinteraction')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_conversation_messages', to='core.organization')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['organization', '-created_at'], name='ai_aiconver_organiz_8077c5_idx'),
        ),
        migrations.AddIndex(
            model_name='aiconversationmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='ai_aiconver_convers_7ed473_idx'),
        ),
        migrations.AddIndex(
            model_name='aiconversationmessage',
            index=models.Index(fields=['organization', '-created_at'], name='ai_aiconver_organiz_bf9a85_idx'),
        ),
    ]
