# Generated by Django 6.0.5 on 2026-07-08 17:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_aiconversation_aiconversationmessage_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReportNarration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('scope', models.CharField(blank=True, help_text="Empty means all scopes -- matches compliance_summary's own scope=None.", max_length=20)),
                ('executive_summary', models.TextField()),
                ('key_highlights', models.JSONField(blank=True, default=list)),
                ('trend_explanations', models.TextField()),
                ('recommendations', models.JSONField(blank=True, default=list, help_text='Advisory suggestions only -- never applied automatically.')),
                ('confidence', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('interaction', models.ForeignKey(help_text='The exact gateway call that produced this narration.', on_delete=django.db.models.deletion.PROTECT, related_name='report_narrations', to='ai.aiinteraction')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_report_narrations', to='core.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'date_from', 'date_to', '-created_at'], name='ai_aireport_organiz_4b357b_idx')],
            },
        ),
    ]
