# Generated by Django 6.0.5 on 2026-07-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_aireportnarration'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinteraction',
            name='response_text',
            field=models.TextField(blank=True),
        ),
    ]
