# Generated by Django 6.0.5 on 2026-07-09 19:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_aiinteraction_response_text'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='aiinteraction',
            constraint=models.UniqueConstraint(condition=models.Q(('outcome', 'OK'), models.Q(('idempotency_key', ''), _negated=True)), fields=('organization', 'idempotency_key'), name='uniq_ai_interaction_ok_per_idempotency_key'),
        ),
    ]
