# Generated by Django 6.0.5 on 2026-07-06 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('core', '0001_initial'),
        ('ingestion', '0005_uploadbatch_calculation_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditChainState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_sequence', models.PositiveBigIntegerField(default=0)),
                ('last_hash', models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Audit Chain State',
                'verbose_name_plural': 'Audit Chain States',
            },
        ),
        migrations.AddField(
            model_name='audittrail',
            name='entry_hash',
            field=models.CharField(help_text="SHA-256 of this entry's canonical payload (including prev_hash) — the chain link.", max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='audittrail',
            name='prev_hash',
            field=models.CharField(help_text="entry_hash of this organization's previous chain entry, or GENESIS_HASH for the first.", max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='audittrail',
            name='sequence',
            field=models.PositiveBigIntegerField(help_text="This organization's monotonic position in its audit chain (1-indexed).", null=True),
        ),
        migrations.AlterField(
            model_name='audittrail',
            name='organization',
            field=models.ForeignKey(help_text='Tenant context of this audit log', on_delete=django.db.models.deletion.PROTECT, related_name='audit_trails', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='audittrail',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AddConstraint(
            model_name='audittrail',
            constraint=models.UniqueConstraint(fields=('organization', 'sequence'), name='unique_org_audit_sequence'),
        ),
        migrations.AddField(
            model_name='auditchainstate',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='audit_chain_state', to='core.organization'),
        ),
    ]
