# Generated by Django 6.0.5 on 2026-07-06 23:08
#
# Phase 6a, final step of the 3-migration sequence (0002 add nullable ->
# 0003 backfill -> 0004 here): now that 0003 has guaranteed every existing
# row has a real sequence/prev_hash/entry_hash, enforce NOT NULL to match
# apps/audit/models.py's actual field definitions.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_backfill_audit_chain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audittrail',
            name='entry_hash',
            field=models.CharField(help_text="SHA-256 of this entry's canonical payload (including prev_hash) — the chain link.", max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='audittrail',
            name='prev_hash',
            field=models.CharField(help_text="entry_hash of this organization's previous chain entry, or GENESIS_HASH for the first.", max_length=64),
        ),
        migrations.AlterField(
            model_name='audittrail',
            name='sequence',
            field=models.PositiveBigIntegerField(help_text="This organization's monotonic position in its audit chain (1-indexed)."),
        ),
    ]
