# Generated by Django 6.0.5 on 2026-07-06 18:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FailedTaskLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_name', models.CharField(db_index=True, help_text='Registered Celery task name, e.g. apps.ingestion.tasks.ingest_task', max_length=255)),
                ('task_id', models.CharField(help_text='The specific Celery task id that failed', max_length=255)),
                ('batch_id', models.CharField(blank=True, db_index=True, help_text='UploadBatch id, extracted from kwargs — both ingest_task and calculate_task pass batch_id as a keyword argument specifically so this extraction never depends on positional-argument order.', max_length=64, null=True)),
                ('workflow_id', models.CharField(blank=True, db_index=True, help_text='Stable cross-task correlation id (UploadBatch.workflow_id), extracted from kwargs the same way as batch_id.', max_length=64, null=True)),
                ('args', models.JSONField(blank=True, default=list)),
                ('kwargs', models.JSONField(blank=True, default=dict)),
                ('exception_type', models.CharField(max_length=255)),
                ('exception_message', models.TextField(blank=True)),
                ('traceback', models.TextField(blank=True)),
                ('retries_attempted', models.IntegerField(default=0, help_text='self.request.retries at the moment of final failure')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Failed Task (Dead Letter)',
                'verbose_name_plural': 'Failed Tasks (Dead Letter)',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task_name', 'created_at'], name='tasks_faile_task_na_95913b_idx')],
            },
        ),
    ]
