# Generated by Django 6.0.5 on 2026-07-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_add_failed_status_and_scope_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadbatch',
            name='parse_errors',
            field=models.JSONField(blank=True, default=list, help_text='Structured, row-addressable parser errors: [{row_index, error}]. Phase 5b: previously returned only in the synchronous upload response and never persisted — since ingestion now runs off the request thread, this is the durable record a client polls for.'),
        ),
    ]
