# Generated by Django 6.0.5 on 2026-07-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0003_uploadbatch_parse_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadbatch',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='The Celery AsyncResult id captured at enqueue time. Not consumed by anything yet — this is what a future cancel endpoint would call AsyncResult(id).revoke() on, captured now so that feature needs no further migration.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='finished_at',
            field=models.DateTimeField(blank=True, help_text='When the job reached a terminal state (COMPLETED/PARTIALLY_COMPLETED/FAILED).', null=True),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='retry_count',
            field=models.IntegerField(default=0, help_text="Celery's own self.request.retries for the processing attempt. Captured for real now (not a placeholder) — always 0 until Phase 5e adds retry policies, at which point this starts reporting real values with no further schema change."),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When processing actually began (set by the task/service, not at batch creation).', null=True),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='worker_id',
            field=models.CharField(blank=True, help_text='Celery worker hostname that processed this batch (self.request.hostname).', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uploadbatch',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Ingestion'), ('QUEUED', 'Queued for Processing'), ('PROCESSING', 'Processing Ingestion'), ('COMPLETED', 'Completed Successfully'), ('PARTIALLY_COMPLETED', 'Partially Completed (Some Rows Failed)'), ('FAILED', 'Failed Ingestion'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=50),
        ),
    ]
