# Generated by Django 6.0.5 on 2026-07-06 14:43

import apps.ingestion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0004_uploadbatch_celery_task_id_uploadbatch_finished_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadbatch',
            name='calculation_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('CALCULATING', 'Calculating'), ('CALCULATED', 'Calculated'), ('CALCULATION_FAILED', 'Calculation Failed')], default='NOT_STARTED', help_text="The carbon-calculation chain link's own status — see CalculationStatus above. Independent of `status`, which reflects ingestion outcome only.", max_length=32),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='pipeline_version',
            field=models.CharField(blank=True, default='1.0', help_text='Version label for the shape of the ingest+calculate pipeline that processed this batch — distinct from EmissionCalculation.engine_version, which versions the carbon-calculation algorithm specifically. Not read by any branching logic yet; pure preparation so a future pipeline restructuring (e.g. a third chain link, chunked processing) can coexist with batches processed under the old shape without a schema redesign.', max_length=32),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='workflow_id',
            field=models.CharField(db_index=True, default=apps.ingestion.models.generate_workflow_id, editable=False, help_text="Stable identifier for this batch's entire processing workflow, threaded unchanged through every chained task (ingest_task, calculate_task, and any future chain links) — independent of each task's own Celery task id, which changes at every hop. Set once at batch creation (CharField, not UUIDField, so it's format-flexible enough to be adopted directly as an OpenTelemetry trace id later without a schema change).", max_length=64),
        ),
        migrations.AlterField(
            model_name='uploadbatch',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text="The id of whichever Celery task is currently active or about to run for this batch — the view sets it to ingest_task's id at enqueue, calculate_task overwrites it with its own id once the chain reaches it. Not consumed by anything yet — this is what a future cancel endpoint would call AsyncResult(id).revoke() on, captured now so that feature needs no further migration.", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uploadbatch',
            name='finished_at',
            field=models.DateTimeField(blank=True, help_text="When the WHOLE chain finished (Phase 5d): set on ingestion's own FAILED path (chain-terminating), or by the calculation stage's completion when ingestion succeeded and the chain continued.", null=True),
        ),
    ]
