# Generated by Django 6.0.5 on 2026-07-06 23:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon', '0003_backfill_reporting_dimensions'),
        ('core', '0001_initial'),
        ('ingestion', '0005_uploadbatch_calculation_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionRecordVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_uuid_backup', models.UUIDField(help_text="Immutable copy of the record ID — survives even if the record itself is ever removed, mirroring AuditTrail's own record_uuid_backup pattern.")),
                ('version_number', models.PositiveIntegerField(help_text="This record's monotonic 1-indexed version position.")),
                ('status', models.CharField(max_length=50)),
                ('is_suspicious', models.BooleanField()),
                ('scope_category', models.CharField(blank=True, max_length=20, null=True)),
                ('normalized_value', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('normalized_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('validation_errors', models.JSONField(blank=True, default=dict)),
                ('raw_data_payload', models.JSONField(help_text="Copy of the record's raw source payload at this point (unchanged in practice today, preserved for completeness/future-proofing).")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('calculation', models.ForeignKey(blank=True, help_text='The EmissionCalculation that was current when this version was snapshotted, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_version_references', to='carbon.emissioncalculation')),
                ('created_by', models.ForeignKey(blank=True, help_text='Best-effort — set only when the caller threads the acting user through via record._version_changed_by.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Denormalized from record — tenant-scoped queries without a join.', on_delete=django.db.models.deletion.PROTECT, related_name='emission_record_versions', to='core.organization')),
                ('record', models.ForeignKey(blank=True, help_text='The record this is a historical snapshot of.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='ingestion.emissionrecord')),
            ],
            options={
                'verbose_name': 'Emission Record Version',
                'verbose_name_plural': 'Emission Record Versions',
                'ordering': ['-version_number'],
                'indexes': [models.Index(fields=['organization', 'created_at'], name='ingestion_e_organiz_a6cdd2_idx')],
                'constraints': [models.UniqueConstraint(fields=('record', 'version_number'), name='unique_record_version')],
            },
        ),
    ]
