# Generated by Django 6.0.5 on 2026-07-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0007_backfill_initial_record_versions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionrecord',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft Ingested'), ('FAILED', 'Failed Validation (Excluded from Calculations)'), ('SUSPICIOUS', 'Suspicious (Needs Review)'), ('VALIDATED', 'Validated (Ready for Approval)'), ('SUBMITTED', 'Submitted for Approval'), ('APPROVED', 'Approved & Audit Locked'), ('REJECTED', 'Rejected (Needs Correction)')], default='DRAFT', max_length=50),
        ),
    ]
