# Generated by Django 6.0.5 on 2026-07-07 14:56

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('ingestion', '0008_workflow_status_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emissionrecord',
            options={'base_manager_name': 'all_objects', 'ordering': ['batch', 'row_index'], 'verbose_name': 'Emission Record', 'verbose_name_plural': 'Emission Records'},
        ),
        migrations.AlterModelManagers(
            name='emissionrecord',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft-delete flag. Never physically deleted -- see EmissionRecord.delete().'),
        ),
        migrations.AddField(
            model_name='emissionrecordversion',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emissionrecordversion',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='batch',
            field=models.ForeignKey(help_text='Source ingestion batch file context', on_delete=django.db.models.deletion.PROTECT, related_name='records', to='ingestion.uploadbatch'),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='organization',
            field=models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.PROTECT, related_name='emission_records', to='core.organization'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['organization', 'is_deleted'], name='ingestion_e_organiz_c79c63_idx'),
        ),
    ]
