# Generated by Django 6.0.5 on 2026-07-10 00:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('ingestion', '0009_soft_delete_and_retention'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['organization', 'status'], name='ingestion_e_organiz_49750c_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadbatch',
            index=models.Index(fields=['status', 'updated_at'], name='ingestion_u_status_95e6b3_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadbatch',
            index=models.Index(fields=['calculation_status', 'updated_at'], name='ingestion_u_calcula_bb6007_idx'),
        ),
    ]
